### ISSUE TITLE
Sync Take via CBF - Tracking issue

### ISSUE THREAD

**Issue by claddyy** [utxo-teleport/teleport-transactions#146]
This acts as a progress tracker for the Summer of Bitcoin project https://github.com/utxo-teleport/teleport-transactions/issues/123. The project proposes the implementation of wallet synchronization using Compact Block Filters (CBF), as described in BIP 157/158, offering a more privacy-preserving approach for synchronization process of Taker wallets. More context [here](https://docs.google.com/document/d/1luhZnAZqcHhKM413DIRYb-t91ENdc-ZhvZvcSC8IP4Q/edit). Individual issues for all of the points below would be documented in a new corresponding issue whose reference would be added as the project progresses.

The following is the approach along with the estimated time for the project.
- [ ] Kickstart: study the Nakamoto library especially the relevant functions used for the CBF syncing. `Week-2`
- [ ] CBF Synchronization: Implementing the synchronization function in `cbf.rs` using the APIs from `Nakamoto` library. `Week 3-6`
- [ ] Balance Calculation: Modify the balance calculation logic to also work with CBF-based sync and implement error handling mechanisms. `Week 7-8`
- [ ] Testing and Documentation: Handle all the edge cases, and write a comprehensive documentation and integration guidelines. `Week 9-12`
