### ISSUE TITLE
swaping HTLC via Taproot+Musig2 tracking issue

### ISSUE THREAD

**Issue by 007harshmahajan** [utxo-teleport/teleport-transactions#147]
implementation of taproot with musig2 for coinswap protocol [https://github.com/utxo-teleport/teleport-transactions/issues/121](url)

- [ ] pubkey exchange and pubnonce exchange flow between parties and implementation 
- [ ] musig2 lib import from [https://github.com/BlockstreamResearch/rust-secp256k1-zkp/pull/48](url)
- [ ] taproot contract script generation 
- [ ] `key path spend` implementation
- [ ] `script path spend` implemenation
